### ISSUE TITLE
Not receiving confirmation code

### ISSUE THREAD

**Issue by nesttle** [stenyak/breakbot#4]
I think there is an error of Yowsup and not Breakbot, but sms/voice is not received!
## 

En español, que me explico mejor, es que no se recibe ni el código sms ni llamada alguna, al querer registrar el número móvil en Whatsapp.

--requestcode sms|voice

status: sent

pero no se recibe nunca el código. En el github de yowsup alguien comentaba que deben ser los headers que usa Yowsup, que pueden ser detectados como obsoletos y por eso no se envía el código; cambiándo estos headers y 'falseando' la versión del dispositivo tampoco se consiguió nada, según un usuario!

Saludos y a ver si se puede solucionar,
enhorabuena por el trabajo!

**Comment by stenyak** [comment]
@nesttle, I have recently tested again the --requestcode funcionality of yowsup, and it seems to be working fine for me.

Since I have limited time, this bug seems related to yowsup (not breakbot), and it's the only complain I've read about it, I'll proceed to close this bug.

If you are still experiencing the same problem and is still not related to breakbot itself, please report the problem at yowsup issue tracker.
